"""Removed the admin_id attribute from the appointments table

Revision ID: 982076f41c00
Revises: 771ebb35d450
Create Date: 2024-02-12 12:21:59.457686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982076f41c00'
down_revision = '771ebb35d450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('appointments_admin_id_fkey', type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('appointments_admin_id_fkey', 'admins', ['admin_id'], ['id'])

    # ### end Alembic commands ###
